In [1]:
import os
import xml.etree.ElementTree as ET
import re
import numpy as np
import pandas as pd
from importlib import reload

In [15]:
f = np.random.uniform(0,1,(2,3,4,7))

In [16]:
f.shape

(2, 3, 4, 7)

In [19]:
f[:,2,:,:].shape

(2, 4, 7)

In [4]:
list(range(-5,1))[-1:0]

[]

In [8]:
a = [[4,5,6], [5,6,7]]
b = np.array(a)
b.shape

(2, 3)

## utils testing

In [2]:
import utils

Using TensorFlow backend.


In [3]:
reload(utils)

corpus = utils.AMI_Corpus(seed=42, embed_vec = "lexvec")

Loading corpus from C:\Users\jakem\Documents\w266\nlp-final-project\data
Begin corpus post-processing ...
Splitting corpus into training and test ...
Creating vocabulary from training set ...
Found 9039 unique words.
Building initial embedding matrix ...
(9041, 300)
loading pretrained vectors from lexvec.commoncrawl.300d.W.pos.neg3.vectors


In [10]:
from math import floor
c_lens = [c.length for c in corpus.train_convos]
print(floor(np.percentile(c_lens, 99)))

511


In [4]:
reload(utils)
ug = utils.UtteranceGenerator(corpus, "train", batch_size = 2, sequence_length = 3)

# cnn testing

In [5]:
import models
reload(models)

<module 'models' from 'C:\\Users\\jakem\\Documents\\w266\\nlp-final-project\\models.py'>

In [17]:
reload(models)
conv_params = {'filters':11, 'kernel_size':7}
model = models.CNN(corpus, batch_size = 2, d1 = 2, d2 = 2, conv_params = conv_params, hidden_units = 64)

In [18]:
reload(models)
model.build_model()

In [19]:
model.compile()

In [20]:
model.model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input (InputLayer)              (None, 5, 31)        0                                            
__________________________________________________________________________________________________
embedding_6 (Embedding)         (None, 5, 31, 300)   2712300     input[0][0]                      
__________________________________________________________________________________________________
Lambda_0 (Lambda)               (None, 31, 300)      0           embedding_6[0][0]                
__________________________________________________________________________________________________
Lambda_1 (Lambda)               (None, 31, 300)      0           embedding_6[0][0]                
__________________________________________________________________________________________________
Lambda_2 (

# lstm (khanpour) testing

In [15]:
import models
reload(models)

<module 'models' from 'C:\\Users\\jakem\\Documents\\w266\\nlp-final-project\\models.py'>

In [16]:
model = models.LSTMSoftmax(corpus = corpus)

In [17]:
model.compile()

In [18]:
model.model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           (None, 31)                0         
_________________________________________________________________
embedding (Embedding)        (None, 31, 300)           2712300   
_________________________________________________________________
dropout_4 (Dropout)          (None, 31, 300)           0         
_________________________________________________________________
lstm_0 (LSTM)                (None, 31, 100)           160400    
_________________________________________________________________
lstm_1 (LSTM)                (None, 31, 100)           80400     
_________________________________________________________________
last_pooling (Lambda)        (None, 100)               0         
_________________________________________________________________
softmax_output (Dense)       (None, 16)                1616      
Total para

In [18]:
a = np.random.uniform(0,1,[3,5])
b = np.random.uniform(0,1,[3,5])
c = np.random.uniform(0,1,[3,5])

In [22]:
np.concatenate([a,b,c], axis = -1).reshape([3,3,-1])

array([[[0.76077096, 0.8200053 , 0.72876689, 0.31541046, 0.98830647],
        [0.88783365, 0.06262905, 0.74536565, 0.77622289, 0.2812459 ],
        [0.1598048 , 0.31897055, 0.19320057, 0.20978853, 0.16901849]],

       [[0.23036959, 0.62677284, 0.28773929, 0.09884658, 0.39402564],
        [0.25722101, 0.89794394, 0.43293834, 0.19150392, 0.14388234],
        [0.09225747, 0.29381216, 0.27614355, 0.8634434 , 0.04363602]],

       [[0.08210017, 0.88536185, 0.61781593, 0.83070299, 0.8109954 ],
        [0.64360088, 0.45852675, 0.94135512, 0.1277848 , 0.54331138],
        [0.82387548, 0.06237041, 0.92876311, 0.44659588, 0.73697109]]])

In [20]:
a

array([[0.76077096, 0.8200053 , 0.72876689, 0.31541046, 0.98830647],
       [0.23036959, 0.62677284, 0.28773929, 0.09884658, 0.39402564],
       [0.08210017, 0.88536185, 0.61781593, 0.83070299, 0.8109954 ]])

In [21]:
b

array([[0.88783365, 0.06262905, 0.74536565, 0.77622289, 0.2812459 ],
       [0.25722101, 0.89794394, 0.43293834, 0.19150392, 0.14388234],
       [0.64360088, 0.45852675, 0.94135512, 0.1277848 , 0.54331138]])

# Hierarchical Bi LSTM CRF

In [11]:
import models

In [25]:
reload(models)
model = models.BiLSTMCRF(corpus = corpus)

In [26]:
model.compile()
model.model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input (InputLayer)              (None, 50, 31)       0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 50, 31, 300)  2712300     input[0][0]                      
__________________________________________________________________________________________________
dropout (Dropout)               (None, 50, 31, 300)  0           embedding[0][0]                  
__________________________________________________________________________________________________
Extraction_0 (Lambda)           (None, 31, 300)      0           dropout[0][0]                    
__________________________________________________________________________________________________
Extraction